### PR TITLE
#1 Update to java:8

### PR DESCRIPTION
**Pull request by egut**
#1 Update to java:8

### CODE REVIEW

**Comment by dlord** [comment]
Please squash commits 15d4efe and 36ad2a3.

Apart from that, is there really a need to switch to Java 8? I have yet to see a real need, since the G1 Garbage Collector is only useful for heaps above 8GB RAM. Anything below that, you're better off using CMS, and CMS sucks in Java 8.

It may be better to just create a branch from this pull request to generate a Java 8-specific image.

**Comment by dlord** [comment]
I'm thinking out loud, so comments are highly appreciated

**Comment by plumbusfactory** [comment]
Some of the newest and some of the most popular plugins only work on 8. (Just a comment )

**Comment by dlord** [comment]
I'm good with this, but please squash commits 15d4efe and 36ad2a3 first before I can process this. I have strict commit standards.

I will be creating a separate docker image tag just for this.

**Comment by egut** [comment]
I actually just used the editor in github to change the 7 -> 8 :)

But you have your git squash.

**Comment by dlord** [comment]
Thank you for squashing the commits. I will merge this now.

**Pull request merged**
